[package]
name = "packagekit"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.71.0"

[dependencies]
config = { git = "https://github.com/joebonrichie/os-tools", rev="48e1fab866df72e65234b90137450b027238d487", package="config" }
moss = { git = "https://github.com/joebonrichie/os-tools", rev="48e1fab866df72e65234b90137450b027238d487", package="moss" }
stone = { git = "https://github.com/joebonrichie/os-tools", rev="48e1fab866df72e65234b90137450b027238d487", package="stone" }
vfs = { git = "https://github.com/joebonrichie/os-tools", rev="48e1fab866df72e65234b90137450b027238d487", package="vfs" }
glib-sys = "0.18"
fs-err = "3.1.1"
itertools = "0.14.0"
url = "2.5.4"
#ffi-convert = "0.6.2"
eyre = "0.6.12"
